apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-app
  namespace: praveen-ns 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitness
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: fitness
    spec:
      containers:
        - name: fitness
          image: muralisocial123/fitness-app:v1.0.1
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-service
  namespace: praveen-ns
spec:
  selector:
    app: fitness
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP

     
